# Generated by Django 5.1.1 on 2024-09-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_drinkscategory_remove_drinks_drink_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinks',
            name='drink',
            field=models.CharField(max_length=2001),
        ),
    ]
